
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.8.2
      chart: ingress-nginx
      helm:
        releaseName: ingress-nginx
        values: |
          controller:
            hostNetwork: true
            kind: DaemonSet
            service:
              enabled: true
              type: NodePort
              nodePorts:
                http: 32222
                https: 30443         
         
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 