apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt

spec:
  acme:
    email: ustaoglusamet05@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
