
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 1.2.11
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets
        # values: |
          
          

         
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 