
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-elasticsearch
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
      chart: elasticsearch 
      helm:
        releaseName: elasticsearch
        values: |
          replicas: 2
          clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

          
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: null
    #   prune: true
    #   selfHeal: false
    #   allowEmpty: false
    # syncOptions:
    #   - Validate=true
    #   - CreateNamespace=true
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true 
    #   - ServerSideApply=true