
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-elasticsearch
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 7.10.2
      chart: elasticsearch 
      helm:
        releaseName: elasticsearch
        values: |
          replicas: 1
          minimumMasterNodes: 1
          clusterHealthCheckParams: "wait_for_status=[yellow,green]&timeout=200s"

          esJavaOpts: "-Xmx1024m -Xms1024m"

          resources:
            limits:
              memory: 6144Mi
            requests:
              cpu: 500m
              memory: 1024Mi

          
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: false
  #   syncOptions:
  #     - Validate=true
  #     - CreateNamespace=true
  #     - PrunePropagationPolicy=foreground
  #     - PruneLast=true 