
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-filebeat
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 7.10.2
      chart: filebeat 
      helm:
        releaseName: filebeat
        values: |
          apmConfig:
            apm-server.yml: |
              apm-server:
                host: "0.0.0.0:8200"

              queue: {}

              output.elasticsearch:
                hosts: ["http://elasticsearch-master:9200"]

          replicas: 1

          resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "1000m"
                memory: "512Mi"

          ingress:
            enabled: true
            path: /
            hosts:
              - apm-server.example.local

          
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true