
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-logstash
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
      chart: logstash 
      helm:
        releaseName: logstash
        values: |
          replicas: 1

          logstashConfig:
            logstash.yml: |
              http.host: "0.0.0.0"
              xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch-master:9200"]

          logstashPipeline:
            logstash.conf: |
              input {
                beats {
                  port => 5044
                }
              }

              output {
                stdout { codec => rubydebug } 

                
              }

          logstashJavaOpts: "-Xmx1g -Xms1g"
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
          service:
            type: ClusterIP
            ports:
              - name: beats
                port: 5044
                protocol: TCP
                targetPort: 5044
              - name: http
                port: 8080
                protocol: TCP
                targetPort: 8080
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #     allowEmpty: false
  #   syncOptions:
  #     - Validate=true
  #     - CreateNamespace=true
  #     - PrunePropagationPolicy=foreground
  #     - PruneLast=true