
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-kibana
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 7.10.2
      chart: kibana 
      helm:
        releaseName: kibana
        values: |
          elasticsearchHosts: "https://elasticsearch-master:9200"
          replicas: 1
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          ingress:
            enabled: true
            path: /
            hosts:
              - kibana.example.local
           

          
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  # syncPolicy:
  #   automated:
  #     prune: false
  #     selfHeal: true
  #     allowEmpty: false
  #   syncOptions:
  #     - Validate=true
  #     - CreateNamespace=true
  #     - PrunePropagationPolicy=foreground
  #     - PruneLast=true