
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-filebeat
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
      chart: filebeat 
      helm:
        releaseName: filebeat
        values: |
          filebeatConfig:
            filebeat.yml: |
              output.logstash:
                 hosts: ['logstash-logstash:5044']

          
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
      - ServerSideApply=true