
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-kibana
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      targetRevision: 8.5.1
      chart: kibana 
      helm:
        releaseName: kibana
        values: |
          replicas: 1
          ingress:
            enabled: true
            path: /
            hosts:
              - kibana.example.local
           

          
                              
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: null
    #   prune: true
    #   selfHeal: false
    #   allowEmpty: false
    # syncOptions:
    #   - Validate=true
    #   - CreateNamespace=true
    #   - PrunePropagationPolicy=foreground
    #   - PruneLast=true 
    #   - ServerSideApply=true