
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-action
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://actions-runner-controller.github.io/actions-runner-controller

      targetRevision: 0.23.5
      chart: actions-runner-controller
      helm:
        releaseName: github-action
        values: |
          syncPeriod: 1m
                   
  destination:
    server: https://kubernetes.default.svc
    namespace: github-action
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true