
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd

spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 13.9.0
      chart: mongodb
      helm:
        releaseName: mongodb
        values: |
          architecture: replicaset
          replicaCount: 1
          useStatefulSet: true
          auth:
            existingSecret: "mongodb-creds"
            usernames:
            - hepapi
            databases:
            - TaskManager       

         
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 