apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-app-chart.fullname" . }}
  namespace: default
  labels:
    {{- include "python-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "python-app-chart.selectorLabels" . | nindent 4 }}
