---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub
  namespace: argocd
spec:
  encryptedData:
    image-repo-token: AgAme0nBGcEjvp3fSKWBo4d3hVKqmsWJAGB5fDe74c/FQuvyAQ6g3xV6abKd2Kf1AjClulllmeghd2WbdNMMCoXs8FIQ9ItT8AP8jhd483X5EZNn2SOzFTrVBWIME5Hr2tIjFaNYGeukZdmCPXUMo6BA1vaVQR8mkRbsEt46aq3icSd8SOfELkSvC5a02KuEEuilRHsIM7rVyUzMZn/z/gB+tEZG6SyJxfGM+nCmNhDBU5pic8yjVjveAJm4GiFQ4Sss2yQO/2YnL6cnddaWTpVctKuIex9sAU8rRpPi+LgEXFor38RzF4x+RAFueWePuN2P4Z6wFtqHdhS9D9pe+W0wV4AK/rPXkL1JuMfJtsBkVCeismUqAmiAw8VIQCm8Jj/Rj1D83IxphMMfloZlHa2YW3TrkhFyabjS/0Ee+DnoL0kaEX8vlqxCYMhheUrhhtY4rKMGWKJq/85C0/nsP9jMgDSQQWN7Sz3ximf7xQlXFtZd8eUqw40oDuEX0d3f4MwMq5YsnMx//NSHnDobRjRtnSyTdhaiSnAcSmcV8db8lY+Hovjlh2gX8S3tR1VtCiaJdnz7yH6Za1VrgLKs9MFFqFYo9Demd+cWCh3pA8PpqtQzgSPTt2ry15LH8evJ9AWR+iX0Fnm3J95MQw1cM/sQ5D/owLbKPUwbLk5hmuym6Cp9RUvGMEejfthaYe/3dHPJlgHvY1JBQ+UXqPRQjbKEZzOpFLulZjy9c8FBRaC6kr07EYPpuYpq5DdJfkt4DcGSjw==
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub
      namespace: argocd
    type: Opaque
